server:
  port: ${PORT:8080}
spring:
  data:
    mongodb:
      auto-index-creation: true
  resources:
    static-locations:
      - classpath:/static/
firebase:
  databaseURL: ${GCP_DATABASE_URL:https://hwc-personal.firebaseio.com}
  serviceAccount: ${GCP_SERVICE_ACCOUNT:${HOME}/serviceAccountKey.json}