# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Maven
        run: cd server && mvn clean install -Pfull
        env:
          CI: false
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          registry: registry.heroku.com
          repository: hwcollections/web
          dockerfile: ./server/src/main/docker/Dockerfile
          path: .
          build_args: JAR_FILE=./server/target/app.jar,UTIL_DIR=./server/src/main/docker/
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a hwcollections web 
